### ISSUE TITLE
U64ArtMap minimum() or maximum() not return minimum or maximum u64 keys and associated value

### ISSUE THREAD

**Issue by Tigranchick** [pgellert/matching-engine#1]
// Reproducing
`let mut map = U64ArtMap::<String>::new();`

```
map.insert(100, "min".to_string());
map.insert(200, "middle".to_string());
map.insert(300, "middle".to_string());
map.insert(400,"max".to_string());
```

```
println!("min: {:?} ", map.minimum_mut());
println!("max {:?} ", map.maximum_mut());
```

Output
min: Some((300, "middle"))
max Some((200, "middle"))

It works differently with various range of numbers, but mostly not as expected. I read the paper of ART and confusing that looks like ART not supporting precise ordering. Correct my guess if  i am wrong and problem in this implementation of ART.
Anyway, your work and dissertation at all are great and interesting.

**Comment by pgellert** [comment]
Hi @Tigranchick, it is flattering that you have read my dissertation. How did you come across it? :)

Thanks for highlighting this. This made me play with this project and Rust a bit more.

Your failing test case was a problem with my implementation. ART stores the keys in sorted order, so it can find the minimum and maximum values in the data structure. I have since then fixed it and added a regression test for your example: https://github.com/pgellert/adaptive-radix-tree/blob/58ae49c0ea36060a45c0e4a077822eebed5d4ef4/tests/u64_art_map.rs#L57-L67
PR: https://github.com/pgellert/adaptive-radix-tree/pull/2

**Comment by Tigranchick** [comment]
Hi! Sorry, I forgot to answer here. Thank you very much for your work, I was doing my own implementation of the matching algorithm. It was very interesting and useful to read your work and code. After you fixed the radix tree, I tested it and everything works great, especially on a large number of orders, but when their moderate quantity binaryheap is more fast. Also, for convenience, I adapted your implementation to decimal IEEE754. While I was studying your matching method, I found another small bug in engine/src/algos/fifa.rs on line 33: 
`while get (Some(ask), Some(bid)) = (self.asks.pop(), self.bids.pop()) {...}`
The bug is that if we have an orderbook with 1 asks and 0 bids or vice versa, then the code in {...} of course will not be executed, but one of the popped order will be dropped. The same is true in engine/src/algos/art_book.rs line: 112. Anyway, thanks again.
